# Generated by Django 5.0.7 on 2024-11-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karatetv', '0007_alter_postse_options_alter_posttv_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttv',
            options={'ordering': ('-created_date',)},
        ),
    ]
